version: '3.8'

services:
  srv: &base
    build: ./docker
    volumes:
      - .:/app
      - target_data:/app/target
      - client_dist:/app/dist
    working_dir: /app
    entrypoint: "cargo watch -x 'run' -i client"
    ports:
      - 8080:8080

  client:
    <<: *base
    entrypoint: trunk watch client/index.html -d dist
    ports:
      - 8000:8000

volumes:
  target_data:
  client_dist:
